name: Tests

on:
  pull_request:
  push:
    branches: ["main", "release/**"]

jobs:

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Run all tests.
        run: go test ./... -cover
